### ISSUE TITLE
[Feat] SettingView - MyProfileView 구현 

### ISSUE THREAD

**Issue by Hongjaaa** [EZPZapp/EZPZ#5]
### Motivation
- 디자인 리팩토링에 따른 뷰 수정 필요

### ToDo
- [ ] 사용자 이름, 속한 커뮤니티, 관심 카테고리 구현
- [ ] 프로필 수정 버튼 구현
- [ ] 캐릭터 이미지 Export
