### ISSUE TITLE
[Feat] - Style, Font Extension

### ISSUE THREAD

**Issue by RuyHa** [EZPZapp/EZPZ#6]
### Motivation
- Style, Font Extension 을 제작하여 앱의 디자인 및 폰트를 통일화 합니다.

### ToDo
- [ ] Style Extension 제작
- [ ] Font Extension 제작
- [ ] Color Extension 제작 (다크모드, 라이트 모드 지원 고려)
